version: '3.9'

services:
  web:
    build:
      context: .
      target: development
    command: npm start
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - BROWSER=none
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env.local
    stdin_open: true
    tty: true
